// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using MesaCore.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace MesaCore.Models
{
    public partial interface IMesaCoreContextProcedures
    {
        Task<List<Sp_GetShipmentsResult>> Sp_GetShipmentsAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
