// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace MesaCore.Models;

public partial class MesaCoreContext : DbContext
{
    public MesaCoreContext(DbContextOptions<MesaCoreContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Shipment> Shipments { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Shipment>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_Shimpents");

            entity.ToTable("SHIPMENTS");

            entity.Property(e => e.Date).HasColumnType("date");
            entity.Property(e => e.PartNumber).IsUnicode(false);
            entity.Property(e => e.ShopOrder).IsUnicode(false);
        });

        OnModelCreatingGeneratedProcedures(modelBuilder);
        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}