// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace MesaCore.Models;

public partial class MesaCoreContext : DbContext
{
    public MesaCoreContext()
    {
    }

    public MesaCoreContext(DbContextOptions<MesaCoreContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Shipment> Shipments { get; set; }

//    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
//#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
//        => optionsBuilder.UseSqlServer("Data Source=WIN-PVPAQO25113;Initial Catalog=MesaCore;User ID=MESINNO03;Password=M3s@.dm1n!");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Shipment>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__SHIPMENT__3214EC0717A39D56");

            entity.ToTable("SHIPMENTS");

            entity.Property(e => e.Date).HasColumnType("datetime");
            entity.Property(e => e.PartNumber).IsUnicode(false);
            entity.Property(e => e.ShopOrder).IsUnicode(false);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}