// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MesaCore.Models;

public partial class Shipment
{
    public int Id { get; set; }

    public int? Packer { get; set; }

    public DateTime? Date { get; set; }

    public string ShopOrder { get; set; }

    public string PartNumber { get; set; }

    public int? Qty { get; set; }
}